In [10]:
import numpy as np # numpy의 별칭으로 np를 지정함

store_a = [20, 10, 30]
store_b = [70, 90, 70]

list_sum = store_a + store_b
list_sum

[20, 10, 30, 70, 90, 70]

In [11]:
np_store_a = np.array(store_a)
np_store_b = np.array(store_b)

array_sum = np_store_a + np_store_b
array_sum

array([ 90, 100, 100])

In [14]:
a = np.array([2, 3, 4])

a.shape, a.ndim, a.dtype, a.itemsize, a.size

((3,), 1, dtype('int64'), 8, 3)

In [19]:
b = np.array([[1, 2, 3],[4, 5, 6]])
b.shape

(2, 3)

In [23]:
z = np.array([10, 20, 30])
q = np.array([1, 2, 3])
z + q

array([11, 22, 33])

In [24]:
z-q

array([ 9, 18, 27])